services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: wp
      MYSQL_USER: wpali
      MYSQL_PASSWORD: wp1234
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - wpnet

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpali
      WORDPRESS_DB_PASSWORD: wp1234
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wpnet
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    networks:
      - wpnet
volumes:
  db_data: {}
  wordpress_data: {}

networks:
  wpnet:
